- name: variables from inventory
  hosts: local
  connection: local
  tasks:
    - name: print the course details
    ansible.builtin.debug:
      msg: "course is {{ Course }}, Duration  is {{ Duration }}, Trainer is {{ Trainer }}"