- name: DevOps course information
  hosts: local
  connection: local
  vars:
   Course: DevOps #string
   Duration: 120 #int
   topics: #list
   - linux
   - shell
   - ansible
   - aws
   live: true #boolean
   tools:
    ci: jenkins
    cloud: aws
    containerization: docker
  tasks:
  - name:  print course information
    ansible.builtin.debug:
      msg: "Hello I am learning {{ Course }}, duration: {{ Duration }}, topics are: {{ topics }}, is it live?: {{ live }}, tools covered are: {{ tools }}" 