- name: variables
  hosts: local
  connection: local
  vars:
   Greet: "PLAY"
  # vars_files:
  # - course.yaml
  # vars_prompt:
  # - name: Greet
  #   prompt: enter the value
  #   private: false
  tasks:
    - name: task level variable
      # vars:
      #   Greet: "task level"
      ansible.builtin.debug:
       msg: "hello {{ Greet }}"

    
    