- name: checking the given number grather than 10 or not
  hosts: local
  connection: local
  tasks:
  - name: print the course details
    ansible.builtin.debud:
      msg: "course is {{ Course }} , Duration is {{ Duration }}, trainer is {{ Trainer }}"