- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug: 
     msg: "Hello {{ person | default ('ramesh') }}"

  - name: converting string to list
    vars:
      fruits: "banana,apple,mango,grapse"
    ansible.builtin.debug:
      msg: "fruits are: {{ fruits | split (' ,') }}"
  - name: converting map to list
    vars:
      course:
        name: "devops with aws"
        duration: 120hrs
        trainer: shivakumar
    ansible.builtin.debug:
      msg: "course info: {{ course  | dict2items }}"
  - name: converting list to map
    vars:
      courses:
      - {'key': 'name', 'value': 'devops with aws'}
      - {'key': 'duration', 'value': '120hrs'}
      - {'key': 'trainer', 'value': 'shivakumar'}
    ansible.builtin.debug:
      msg: "course info: {{ courses | items2dict }}"  
  - name: converting upper to lower
    vars:
      name: "ShIvakumar Reddy M"
    ansible.builtin.debug:
      msg: "Name: {{ name | lower }}"
  - name: converting lower to upper
    vars:
      name: "ShIvakumar Reddy M"
    ansible.builtin.debug:
      msg: "Name: {{ name | upper }}"
  - name: finding max and min numbers
    vars:
      numbers: [ 2,45,89,567,98765 ]
    ansible.builtin.debug:
      msg: "{{ numbers | max }} and {{ numbers | min }}"
  - name: checking ip adress is valid or not
    vars:
      ip: "1234.345.9.5"
    ansible.builtin.debug:
      msg: "ip: {{ ip | ansible.util.ipaddr }}"
